### ISSUE TITLE
Error on XPathSearchPrompt

### ISSUE THREAD

**Issue by sfx2k** [actionshrimp/vim-xpath#12] opened 2016-02-23 12:11 UTC
Hey,

when I call XPathSearchPrompt with my XML-File I got the following Error:

*****

> Error detected while processing C:\Users\itsme\Documents\Programmeinstellungen\Vim\vimfiles\bundle\xpath\autoload\xpath.vim:
line   50:
ValueError: invalid \x escape
line   51:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\itsme\Documents\Programmeinstellungen\Vim\vimfiles\bundle\xpath\autoload/../python/main.py", line 12, in <module>
    import vim_adaptor
ImportError: No module named vim_adaptor
0
Error detected while processing BufRead Auto commands for "*":
E32: No file name
"XPath Search" [New File]-- INSERT ---- INSERT --
Error detected while processing function <SNR>74_XPathChanged[8]..XPathEvaluate:
line    3:
Traceback (most recent call last):
Error detected while processing function <SNR>74_XPathChanged[8]..XPathEvaluate:
line    3:
  File "<string>", line 1, in <module>
Error detected while processing function <SNR>74_XPathChanged[8]..XPathEvaluate:
line    3:
NameError: name 'vim_adaptor' is not defined-- INSERT --
Error detected while processing function <SNR>74_XPathChanged[8]..XPathEvaluate:
line    3:
Traceback (most recent call last):
Error detected while processing function <SNR>74_XPathChanged[8]..XPathEvaluate:
line    3:
  File "<string>", line 1, in <module>
Error detected while processing function <SNR>74_XPathChanged[8]..XPathEvaluate:
line    3:
NameError: name 'vim_adaptor' is not defined
Error detected while processing function <SNR>74_XPathChanged[8]..XPathEvaluate:
line    3:
Traceback (most recent call last):
Error detected while processing function <SNR>74_XPathChanged[8]..XPathEvaluate:
line    3:
  File "<string>", line 1, in <module>
Error detected while processing function <SNR>74_XPathChanged[8]..XPathEvaluate:
line    3:
NameError: name 'vim_adaptor' is not defined
Error detected while processing function XPathComplete[2]..XPathEvaluate:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'vim_adaptor' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'vim_adaptor' is not defined
(1 of 1): Start typing an XPath to search
Error detected while processing function XPathComplete:
line    7:
E553: No more items
Error detected while processing function XPathComplete:
line    7:
E553: No more items

*****

I use Python 2.7.11 (Anaconda 2.5.0) 32bit on Win7 64bit

My Vim-Version:

> VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb  9 2016 08:04:25)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1-1293
Compiled by itsme
Huge version with GUI.  Features included (+) or not (-):
+acl             +byte_offset     +cmdline_hist    +cursorbind      -dnd             +farsi           +gettext/dyn     +keymap          +localmap        +mouseshape      +path_extra      +python/dyn      +scrollbind      -sun_workshop    -tgetent         +vertsplit       +wildignore      -xterm_save
+arabic          +channel         +cmdline_info    +cursorshape     -ebcdic          +file_in_path    -hangul_input    +langmap         -lua             +multi_byte      -perl            -python3         +signs           +syntax          -termresponse    +virtualedit     +wildmenu        +xpm_w32
+autocmd         +cindent         +comments        +dialog_con_gui  +emacs_tags      +find_in_path    +iconv/dyn       +libcall         +menu            +multi_lang      +persistent_undo +quickfix        +smartindent     +tag_binary      +textobjects     +visual          +windows         
+balloon_eval    +clientserver    +conceal         +diff            +eval            +float           +insert_expand   +linebreak       +mksession       -mzscheme        -postscript      +reltime         -sniff           +tag_old_static  +title           +visualextra     +writebackup     
+browse          +clipboard       +cryptv          +digraphs        +ex_extra        +folding         +job             +lispindent      +modify_fname    -netbeans_intg   +printer         +rightleft       +startuptime     -tag_any_white   +toolbar         +viminfo         -xfontset        
++builtin_terms  +cmdline_compl   +cscope          -directx         +extra_search    -footer          +jumplist        +listcmds        +mouse           +ole             +profile         -ruby            +statusline      -tcl             +user_commands   +vreplace        -xim             
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32   -DFEAT_CSCOPE  -DFEAT_CHANNEL   -DFEAT_XPM_W32   -DWINVER=0x500 -D_WIN32_WINNT=0x500  /Fo.\ObjGOYi386/ /Ox /GL -DNDEBUG  /Zl /MT -DFEAT_OLE -DFEAT_GUI_W32 -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_PYTHON -DDYNAMIC_PYTHON  -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_HUGE /Fd.\ObjGOYi386/ /Zi
Linking: link /RELEASE /nologo /subsystem:windows /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:i386 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib  /machine:i386 /nodefaultlib libcmt.lib oleaut32.lib user32.lib      /nodefaultlib:python27.lib     WSock32.lib xpm\x86\lib\libXpm.lib /PDB:gvim.pdb -debug

*****

Any ideas?

Best Regards

**Comment by actionshrimp** [comment] 2016-02-23 14:56
Hey, can you send through a minimum XML file that replicates the problem, along with an XPath you're typing when it happens? (Or if it happens for every XPath please just say that). It looks like there may be a character that is either invalid or not being handled correctly by the plugin.

In particular this part of the error message: `ValueError: invalid \x escape` makes me wonder whether you have `\x` in your file anywhere?

Thanks
Dave

**Comment by sfx2k** [comment] 2016-02-23 19:03
Hi,

I can reproduce this with every - even empty - XMLFile.
Just create test.xml, open it in Vim and type :XPathSearchPrompt.
The error occurs immediately after pressing Enter - I have no chance to enter a XPath :(

**Comment by sfx2k** [comment] 2016-02-24 12:45
Even if I call XPathSearchPrompt on emtpy buffer results in this Error :(

![snap20160224134028186](https://cloud.githubusercontent.com/assets/4921498/13285755/c0e9ea88-dafc-11e5-9e1d-683095dc229b.png)
![snap20160224134035609](https://cloud.githubusercontent.com/assets/4921498/13285756/c1121742-dafc-11e5-910e-5815e25ede89.png)
![snap20160224134058699](https://cloud.githubusercontent.com/assets/4921498/13285757/c1135eb8-dafc-11e5-980f-db65663d211c.png)
![snap20160224134103757](https://cloud.githubusercontent.com/assets/4921498/13285758/c11507f4-dafc-11e5-8d85-771f421be01e.png)

**Comment by sfx2k** [comment] 2016-02-24 13:47
New findings:

when I rename the Plugin-Directory from '\bundle\**x**path' to '\bundle\**y**path' the first error (invalid \x escape) does not appear.
It seems, windows path separators where not handled correctly in this case (bundle**\x**path)

But the second still appears (vim_adaptor not defined)

**Comment by sfx2k** [comment] 2016-02-24 14:04
Ok, I got it.

sys.argv[0] in main.py seems to be broken, too.

The result is:

C:\Users\itsme\Documents\Programmeinstellungen\Vim^Kimfiles^Hundle^Kim_xpath^Gutoload/../python/main.py

This is *urgs*

If I set it to

"C:\Users\itsme\Documents\Programmeinstellungen\Vim\vimfiles\bundle\vim_xpath\python\main.py"

manually, everything works fine.

Would be nice, if you can fix those two issues (\x and SCRIPT_FILE).

Thanks in advance.

**Comment by actionshrimp** [comment] 2016-02-24 16:57
Aha, good find! Looks like this area of the plugin might be the cause of the issues:

https://github.com/actionshrimp/vim-xpath/blob/master/autoload/xpath.vim#L44

Hardcoding the part of the path with `/` seems obviously wrong, but I'm not sure how the `\x` part you mentioned comes into play there.

What's strange is I used to use the plugin on Windows just fine, although that was a while back. Do you have `shellslash` set or anything like that?

**Comment by sfx2k** [comment] 2016-02-24 18:46
As mentioned before, I work with a blank _vimrc => noshellslash

**Comment by actionshrimp** [comment] 2016-02-25 11:45
Pretty sure your PR fixed both the problems you were having, so closing this now.

**Closed by actionshrimp** 2016-02-25 11:45 UTC
